"""iptables 어댑터.

iptables-restore가 그대로 읽을 수 있는 완전한 설정 파일을 생성합니다.
- 정책 셋 전체를 매번 다시 생성하는 선언형 방식 (드리프트 방지)
- iptables-restore는 파일 전체를 원자적으로 적용하므로,
  적용 도중 일부 정책만 반영되는 반쪽 상태가 생기지 않습니다.
- 기본 정책은 DROP (deny-by-default): 명시적으로 허용하지 않은
  트래픽은 모두 차단하는 화이트리스트 방식.
"""

from __future__ import annotations

from policygate.adapters.base import CommandRunner, FirewallAdapter
from policygate.rule import Action, FirewallRule, Protocol, format_ports


class IptablesAdapter(FirewallAdapter):
    name = "iptables"

    #: 관리 대상 체인. FORWARD 체인(경유 트래픽)을 기본으로 관리
    chain = "FORWARD"

    def __init__(self, runner: CommandRunner | None = None):
        self.runner = runner  # None이면 render 전용 (dry-run 모드)

    def render(self, rules: list[FirewallRule]) -> str:
        lines = [
            "# Generated by PolicyGate — 수동 편집 금지",
            "*filter",
            ":INPUT ACCEPT [0:0]",
            f":{self.chain} DROP [0:0]",   # deny-by-default
            ":OUTPUT ACCEPT [0:0]",
            # 연결 추적: 이미 허용된 세션의 응답 패킷은 통과
            f"-A {self.chain} -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT",
        ]
        for rule in sorted(rules, key=lambda r: (r.priority, r.rule_id)):
            lines.extend(self._render_rule(rule))
        lines.append("COMMIT")
        return "\n".join(lines) + "\n"

    def _render_rule(self, rule: FirewallRule) -> list[str]:
        target = "ACCEPT" if rule.action == Action.ALLOW else "DROP"
        base = [f"-A {self.chain}"]
        if rule.src != "0.0.0.0/0":
            base.append(f"-s {rule.src}")
        if rule.dst != "0.0.0.0/0":
            base.append(f"-d {rule.dst}")

        comment = f'-m comment --comment "{rule.rule_id}"'

        if rule.protocol == Protocol.ANY:
            # 프로토콜 무관 정책이라도 포트 지정이 있으면 tcp/udp로 분해
            if rule.dst_ports != ((1, 65535),):
                out = []
                for proto in ("tcp", "udp"):
                    out.append(" ".join(
                        base + [f"-p {proto}", self._ports(rule), comment, f"-j {target}"]
                    ))
                return out
            return [" ".join(base + [comment, f"-j {target}"])]

        parts = base + [f"-p {rule.protocol.value}"]
        if rule.protocol != Protocol.ICMP and rule.dst_ports != ((1, 65535),):
            parts.append(self._ports(rule))
        parts += [comment, f"-j {target}"]
        return [" ".join(parts)]

    @staticmethod
    def _ports(rule: FirewallRule) -> str:
        # multiport는 콜론(:) 구분 범위 문법을 사용
        spec = format_ports(rule.dst_ports).replace("-", ":")
        return f"-m multiport --dports {spec}"

    def deploy(self, rules: list[FirewallRule]) -> str:
        rendered = self.render(rules)
        if self.runner is None:
            # 러너가 없으면 실제 반영 없이 설정만 반환 (안전 기본값)
            return rendered
        self.runner.run(["iptables-restore"], input_text=rendered)
        return rendered
