"""nftables 어댑터.

`nft -f` 로 그대로 적용 가능한 선언형 룰셋 파일을 생성합니다.
어댑터 계층의 가치를 보여주는 두 번째 구현체:
동일한 FirewallRule 모델이 완전히 다른 문법으로 변환됩니다.
"""

from __future__ import annotations

from policygate.adapters.base import CommandRunner, FirewallAdapter
from policygate.rule import Action, FirewallRule, Protocol


class NftablesAdapter(FirewallAdapter):
    name = "nftables"

    table = "policygate"
    chain = "forward"

    def __init__(self, runner: CommandRunner | None = None):
        self.runner = runner

    def render(self, rules: list[FirewallRule]) -> str:
        lines = [
            "# Generated by PolicyGate — 수동 편집 금지",
            f"flush table inet {self.table}",  # 전체 교체 (선언형)
            f"table inet {self.table} {{",
            f"  chain {self.chain} {{",
            # deny-by-default + 기존 세션 응답 허용
            "    type filter hook forward priority 0; policy drop;",
            "    ct state established,related accept",
        ]
        for rule in sorted(rules, key=lambda r: (r.priority, r.rule_id)):
            lines.append("    " + self._render_rule(rule))
        lines += ["  }", "}"]
        return "\n".join(lines) + "\n"

    def _render_rule(self, rule: FirewallRule) -> str:
        parts: list[str] = []
        if rule.src != "0.0.0.0/0":
            parts.append(f"ip saddr {rule.src}")
        if rule.dst != "0.0.0.0/0":
            parts.append(f"ip daddr {rule.dst}")

        if rule.protocol == Protocol.ICMP:
            parts.append("ip protocol icmp")
        elif rule.protocol in (Protocol.TCP, Protocol.UDP):
            if rule.dst_ports != ((1, 65535),):
                parts.append(f"{rule.protocol.value} dport {self._ports(rule)}")
            else:
                parts.append(f"ip protocol {rule.protocol.value}")
        elif rule.protocol == Protocol.ANY and rule.dst_ports != ((1, 65535),):
            # any 프로토콜 + 포트 지정: meta l4proto로 tcp/udp 동시 매칭
            parts.append(f"meta l4proto {{ tcp, udp }} th dport {self._ports(rule)}")

        verdict = "accept" if rule.action == Action.ALLOW else "drop"
        parts.append(f'{verdict} comment "{rule.rule_id}"')
        return " ".join(parts)

    @staticmethod
    def _ports(rule: FirewallRule) -> str:
        items = [
            f"{lo}" if lo == hi else f"{lo}-{hi}" for lo, hi in rule.dst_ports
        ]
        return items[0] if len(items) == 1 else "{ " + ", ".join(items) + " }"

    def deploy(self, rules: list[FirewallRule]) -> str:
        rendered = self.render(rules)
        if self.runner is None:
            return rendered
        self.runner.run(["nft", "-f", "-"], input_text=rendered)
        return rendered
